name: gooble_goblin
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  any_link_preview: ^3.0.1
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_3d_controller: ^2.3.0
  flutter_local_notifications: ^19.5.0
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^4.0.3
  flutter_svg: ^2.2.3
  flutter_timezone: ^5.0.1
  font_awesome_flutter: ^10.12.0
  fpdart: ^1.2.0
  gap: ^3.0.1
  google_fonts: ^6.3.3
  local_auth: ^3.0.0
  logger: ^2.6.2
  model_viewer_plus: ^1.9.3
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  sqflite_live: ^1.0.2
  uuid: ^4.4.0
  syncfusion_flutter_chat: ^32.1.21
  timezone: ^0.10.1
  toastification: ^3.0.3
  url_launcher: ^6.3.1
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/3d_model/
    - assets/app_icon/
    - assets/images/

flutter_native_splash:
  color: "#000000" # Dark background to match animation
  image: assets/app_icon/app_icon_dark_mode.png # Your logo/image (centered static)
  android: true
  ios: true
